### ISSUE TITLE
Getting Error detecting mode client_error: client error: 404 on running "kubectl advisory" command

### ISSUE THREAD

**Issue by anmolsaini-hpe** [elisasre/kubernetes-resource-advisor#88]
Hi Team,

I followed the instructions to install the resource advisor on my Mac machine and was able to run the command "kubectl advisory --help" but facing an issue while running the command "kubectl advisory". Could you please help me here or guide me how to run the tool for a particular namespace?

Thanks!

**Comment by rofafor** [comment]
Are you having prometheus-operator installed in your cluster? Unfortunately the tool nor its documentation state that out and loud.

If you're having prometheus up and running, another issue is that the the prometheus address is currently hard-coded under `monitoring` namespace:
https://github.com/elisasre/kubernetes-resource-advisor/blob/main/pkg/advisor/utils.go#L25

**Comment by anmolsaini-hpe** [comment]
I did a fresh installation of the Prometheus operator using helm in the "monitoring" namespace:
helm install prom prometheus-community/kube-prometheus-stack --namespace monitoring

Do I need to make a change in the file you mentioned above?

Now I am getting error:
Error detecting mode server_error: server error: 503

**Comment by anmolsaini-hpe** [comment]
Also, can I use this advisory tool if I am using Thanos to scrape Multiple Kubernetes clusters?

**Comment by rofafor** [comment]
Auto-detection of prometheus was just added in https://github.com/elisasre/kubernetes-resource-advisor/pull/89

Thanos support doesn't work out-of-box, but requires some code tweaks for accessing the data

**Comment by anmolsaini-hpe** [comment]
Here the pods running :
kubectl get pods
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prom-kube-prometheus-stack-alertmanager-0   2/2     Running   0          84m
prom-grafana-85494cfccf-82n5d                            3/3     Running   0          84m
prom-kube-prometheus-stack-operator-7cbc879f74-f5xxv     1/1     Running   0          84m
prom-kube-state-metrics-6cb58b5b8c-nsrwq                 1/1     Running   0          84m
prom-prometheus-node-exporter-hvm2q                      1/1     Running   0          84m
prometheus-prom-kube-prometheus-stack-prometheus-0       2/2     Running   0          84m

I can hit the prometheus using port-forward :

kubectl -n monitoring port-forward svc/prom-kube-prometheus-stack-prometheus 9090:9090


I re-installed the kubectl advisory and still getting :

Error detecting mode server_error: server error: 503

**Comment by rofafor** [comment]
The tool is accessing the prometheus via this service through k8s api:
```
% kubectl get services -l operated-prometheus=true -A
NAMESPACE    NAME                  TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
monitoring   prometheus-operated   ClusterIP   None         <none>        9090/TCP   2y110d
```

**Comment by anmolsaini-hpe** [comment]
Here is the svc running on my cluster :

kubectl get services -l operated-prometheus=true -A

NAMESPACE    NAME                  TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
monitoring   prometheus-operated   ClusterIP   None         <none>        9090/TCP   97m

**Comment by rofafor** [comment]
So the service is there, good.  The access to Prometheus API is actually proxied through k8s API:
```
% kubectl proxy –api-prefix=/api
Starting to serve on 127.0.0.1:8001

% curl http://127.0.0.1:8001/api/v1/namespaces/monitoring/services/prometheus-operated:web/proxy/
<a href="/graph">Found</a>.
```

**Comment by anmolsaini-hpe** [comment]
kubectl proxy –api-prefix=/api
Starting to serve on 127.0.0.1:8001

curl http://127.0.0.1:8001/api/v1/namespaces/monitoring/services/prometheus-operated:web/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"prometheus-operated:web\"",
  "reason": "ServiceUnavailable",
  "code": 503

**Comment by rofafor** [comment]
Most probably your Helm installer is using a different port name (`http-web`) than our hard-coded one (`web`). Could you check whether this one works for you:
```
curl http://127.0.0.1:8001/api/v1/namespaces/monitoring/services/prometheus-operated:http-web/proxy/
```

I made a preliminary autodetection for it: https://github.com/elisasre/kubernetes-resource-advisor/pull/90

**Comment by anmolsaini-hpe** [comment]
curl http://127.0.0.1:8001/api/v1/namespaces/monitoring/services/prometheus-operated:http-web/proxy/
<a href="/graph">Found</a>.

**Comment by zetaab** [comment]
@anmolsaini-hpe you could try again with 1.1.0 version

**Comment by anmolsaini-hpe** [comment]
Thanks!
I tried with 1.1.0 and got:

kubectl advisory
could not find cpu mode

is it expected?

**Comment by rofafor** [comment]
> is it expected?

Nope. It doesn't find any suitable data in your Prometheus. We are using this recording rule `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate`:
https://github.com/prometheus-community/helm-charts/blob/28f6cf79a22025d066528b0f3561314a242e46f0/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L27-L42

![image](https://github.com/elisasre/kubernetes-resource-advisor/assets/9297850/5f3d4376-7179-4d6e-8165-c14b1764f23f)

You need to figure out, why there's no data in your Prometheus or why that recording rule is missing.
